# Generated by Django 5.0.8 on 2024-09-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('IdCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='IdCargo')),
                ('TipoDoc', models.CharField(max_length=30, verbose_name='Tipo Documento')),
                ('NroDoc', models.CharField(max_length=15, verbose_name='Numero Documento')),
                ('NombreCompleto', models.CharField(max_length=255, verbose_name='NombreCompleto   ')),
                ('FechaNac', models.DateField(verbose_name='FechaNac Nacimiento')),
                ('Direccion', models.CharField(max_length=255, verbose_name='Direccion ')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='password')),
                ('Telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('Estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('UsuarioCrea', models.IntegerField(blank=True, null=True, verbose_name='UsuarioCrea')),
                ('FechaCreacion', models.DateTimeField(null=True, verbose_name='FechaCreacion')),
                ('UsuarioModifica', models.IntegerField(null=True, verbose_name='UsuarioModifica')),
                ('FechaModificado', models.DateTimeField(null=True, verbose_name='FechaModificado')),
                ('IdUbigeo', models.ForeignKey(db_column='IdUbigeo', on_delete=django.db.models.deletion.CASCADE, to='empleados.ubigeo', verbose_name='Ubigeo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'managed':False,
            },
        ),
    ]
