# Generated by Django 5.0.8 on 2024-09-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('IdCargo', models.AutoField(primary_key=True, serialize=False, verbose_name='IdCargo')),
                ('NombreCargo', models.CharField(max_length=50, verbose_name='Descripcion del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargo',
                'managed':False,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('IdUbigeo', models.AutoField(primary_key=True, serialize=False, verbose_name='IdUbigeo')),
                ('Ubigeo', models.CharField(max_length=50, null=True, verbose_name='Ubigeo')),
                ('Distrito', models.CharField(max_length=255, null=True, verbose_name='Distrito')),
                ('Provincia', models.CharField(max_length=255, null=True, verbose_name='Provincia')),
                ('Departamento', models.CharField(max_length=255, null=True, verbose_name='Departamento')),
                ('Ubicacion', models.CharField(max_length=255, null=True, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Ubigeo',
                'verbose_name_plural': 'Ubigeos',
                'db_table': 'Ubigeo',
                'managed':False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDoc', models.CharField(max_length=30, verbose_name='TipoDoc')),
                ('NroDoc', models.CharField(max_length=15, verbose_name='NroDoc')),
                ('NombreCompleto', models.CharField(max_length=255, verbose_name='NombreCompleto')),
                ('FechaNac', models.DateField(verbose_name='FechaNac')),
                ('Direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('Estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('FechaCreacion', models.DateField(auto_now_add=True, verbose_name='FechaCreacion')),
                ('IdCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.cargo', verbose_name='Cargo')),
                ('IdUbigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.ubigeo', verbose_name='Ubigeo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'managed':False,
            },
        ),
    ]
